// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxihevuorcjnswbzildj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14aWhldnVvcmNqbnN3YnppbGRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMDQyNDAsImV4cCI6MjA2MjU4MDI0MH0.MsYuWrTs59tv2eutF-MS3GwMC77ri9_no-6jcLoWtig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);